# Generated by Django 4.2.28 on 2026-02-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formatotesismodel',
            name='carrera',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='formatotesismodel',
            name='incluye',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='formatotesismodel',
            name='version',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='promptmodel',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='promptmodel',
            name='recomendado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promptmodel',
            name='tipo_documento',
            field=models.CharField(choices=[('tesis_completa', 'Tesis Completa'), ('resumen_intro', 'Solo Resumen/Intro'), ('marco_teorico', 'Marco Teórico'), ('articulo', 'Artículo Científico'), ('otro', 'Otro')], default='tesis_completa', max_length=50),
        ),
        migrations.AddField(
            model_name='proyectomodel',
            name='formato_label',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='proyectomodel',
            name='horas_estimadas',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='proyectomodel',
            name='prompt_titulo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='proyectomodel',
            name='titulo',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='proyectomodel',
            name='tokens_usados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='proyectomodel',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('error', 'Error')], default='procesando', max_length=50),
        ),
        migrations.AlterField(
            model_name='proyectomodel',
            name='usuario',
            field=models.CharField(default='anon', max_length=255),
        ),
    ]
